// <auto-generated />
using System;
using DemoHotel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoHotel.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20230503144623_OneToMany")]
    partial class OneToMany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DemoHotel.Models.Chambre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("chambre_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NbLit")
                        .HasColumnType("int")
                        .HasColumnName("nb_lit");

                    b.Property<int?>("ReservationId1")
                        .HasColumnType("int");

                    b.Property<int>("Statut")
                        .HasColumnType("int")
                        .HasColumnName("statut");

                    b.Property<decimal>("Tarif")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("tarif");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId1");

                    b.ToTable("Chambres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NbLit = 2,
                            Statut = 0,
                            Tarif = 32.25m
                        },
                        new
                        {
                            Id = 2,
                            NbLit = 4,
                            Statut = 0,
                            Tarif = 62.25m
                        },
                        new
                        {
                            Id = 3,
                            NbLit = 6,
                            Statut = 0,
                            Tarif = 82.25m
                        },
                        new
                        {
                            Id = 4,
                            NbLit = 3,
                            Statut = 0,
                            Tarif = 52.25m
                        });
                });

            modelBuilder.Entity("DemoHotel.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nom");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prenom");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("telephone");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("DemoHotel.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    b.Property<int>("statut")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("DemoHotel.Models.Chambre", b =>
                {
                    b.HasOne("DemoHotel.Models.Reservation", "Reservation")
                        .WithMany("Chambres")
                        .HasForeignKey("ReservationId1");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("DemoHotel.Models.Reservation", b =>
                {
                    b.HasOne("DemoHotel.Models.Client", "Client")
                        .WithMany("Reservartions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("DemoHotel.Models.Client", b =>
                {
                    b.Navigation("Reservartions");
                });

            modelBuilder.Entity("DemoHotel.Models.Reservation", b =>
                {
                    b.Navigation("Chambres");
                });
#pragma warning restore 612, 618
        }
    }
}
